name: Portal CI

on: [push, pull_request]

jobs:
  build:

    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '2.7' # Needs to match version used by github pages.
    - name: Install Ruby dependencies
      run: cd docs; bundle install; cd -

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.1.0'
    - name: Install Node dependencies
      run: npm ci

    - name: Run test script
      run: ./test.sh
